server:
  port: 8081
  error:
    include-stacktrace: never
  shutdown: graceful

spring:
  application:
    name: ledger-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  lifecycle:
    timeout-per-shutdown-phase: 20s
  flyway:
    enabled: true
    locations: classpath:db/migration
    check-location: true
    create-schemas: true
    schemas: ledger
    default-schema: ledger
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ledger
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:app}
    password: ${SPRING_RABBITMQ_PASSWORD:app}
    # Do not create RabbitAdmin, do not auto-declare topology
    dynamic: false
    listener:
      simple:
        # Don't fail startup if queue missing; consolidator owns topology
        missing-queues-fatal: false
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true

  amqp:
    admin:
      # If a RabbitAdmin bean exists for some reason, keep it from running
      auto-startup: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    git:
      mode: simple
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${HOSTNAME:local}

api:
  key: ${API_KEY:}

springdoc:
  swagger-ui:
    path: /swagger

outbox:
  drainDelay: 500
  batchSize: 200
  maxAttempts: 20
logging:
  level:
    root: INFO
    org.flywaydb: INFO

app:
  cors:
    # Comma-separated origins for CORS (defaults to http://localhost:3000)
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
