name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Build (skip tests)
        run: mvn -q -DskipTests=true package
      - name: Compose up
        run: docker compose up -d --build
      - name: Run test suite (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: bash ops/test-suite.sh --no-teardown --load
      - name: Run test suite (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: pwsh -ExecutionPolicy Bypass -File ops/test-suite.ps1 -NoTeardown -Load
      - name: Upload request/response evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-requests-${{ matrix.os }}
          path: out
      - name: Export logs on failure
        if: failure()
        run: |
          mkdir -p out
          docker compose ps > out/compose-ps.txt || true
          docker compose logs --no-color --since=10m > out/compose-logs.txt || true
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs-${{ matrix.os }}
          path: |
            out/compose-ps.txt
            out/compose-logs.txt
